version: "3.4"

services:
  golang:
    image: golang:1.9.6
    volumes:
      - .:/go
  glide:image: instrumentisto/glide
            volumes:
              - .:/go
            working_dir: /go
    image: instrumentisto/glide
    volumes:
      - .:/go
    working_dir: /go