version: "3.4"

services:
  golang:
    image: golang:1.9.6
    volumes:
      - .:/go
  glide:
    image: instrumentisto/glide
    volumes:
      - ./src/${PROJECT_NAME}:/go/src/${PROJECT_NAME}
    working_dir: /go/src/${PROJECT_NAME}